### ISSUE TITLE
LSS_A/LSS_B non-inverting amplifier ignores negative voltage? 

### ISSUE THREAD

**Issue by OxygenLiu** [dzid26/StepperServo-hardware#2]
Depending on the forward or reverse rotation, LSS_A and LSS_B vary between -0.33 and +0.33V. 

However, the OpAmp LV321 has only positive supply of +3.3V, there is no negative supply of -3.3V or voltage offset, it appears to me the negative voltage is ignored.

**Comment by dzid26** [comment]
No, LSS_x  cannot be negative. 
(Notice sense resistor is connected to the ground and so current will typically flow in one direction. Unless BEMF is higher than supply).
This is called [low side current sensing](https://docs.simplefoc.com/low_side_current_sense) and is much simpler (especially with this design, since the sense resistors were already there), but it only can measure current when the H-bridge is conducting current. For this reason, the reading needs to be synchronized with the driver.

For current control where the A4950 chip controls the current, we don't know when it is transmitting the current. So the only choice is to oversamople and measure some average current.  This can't be used for any type of control (and does need to be since the chip is in control), but could be useful for some diagnostic (basically telling whether there is current or not). 

In voltage control, on which I started [working on](https://github.com/dzid26/StepperServoCAN/tree/voltage-control)  it is possible to precisely synchronize the reading.  But I haven't implemented it. 

So right now the current sensing is not used.  The op amps are nice though, because thanks to the amplification,  even now if you can easily measure the current waveform with a scope (albeit with gaps when H-bridge not conducting).
